---
- name: Install and Configure Slurm on EC2 Instances
  hosts: all
  gather_facts: yes
  tasks:
    - name: Load inventory hosts
      set_fact:
        inventory: "{{ groups['all'] }}"  # Use 'all' or another group name as needed

    - name: Remove old SSH host keys
      command: ssh-keygen -f '/root/.ssh/known_hosts' -R "{{ item }}"
      loop: "{{ hostvars[item].ansible_host }}"
      ignore_errors: yes
      delegate_to: localhost

    - name: Ensure all instances are reachable
      wait_for:
        host: "{{ hostvars[item].ansible_host }}"
        port: 22
        state: started
        delay: 10
      loop: "{{ inventory }}"
      delegate_to: localhost

    - name: Distribute public SSH key to all instances
      authorized_key:
        user: ubuntu
        state: present
        key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
      loop: "{{ inventory }}"
      delegate_to: master
      become: yes

    - name: Test SSH connectivity as root
      command: ssh -o StrictHostKeyChecking=no -i /root/.ssh/boot-1.pem root@{{ hostvars[item].ansible_host }} echo "Connected"
      register: ssh_test
      ignore_errors: yes
      loop: "{{ inventory }}"
      delegate_to: localhost

    - name: Print SSH connectivity results
      debug:
        msg: "{{ ssh_test.results }}"